### ISSUE TITLE
Building settings?

### ISSUE THREAD

**Issue by IvanAli** [zmeadows/lldbg#1]
What is the compiler you are using for make to build on Mac OS? I tried both clang and g++-10.1, but they complain about <filesystem> not found and a bunch of errors respectively.

**Comment by zmeadows** [comment]
Hey, thanks for taking an interest! I've been on vacation for a couple weeks, but I will address this in the next few days. The only real issue is that CMakeLists.txt needs to be configured to find the LLDD library on Mac OS. I'll also update the readme with proper build instructions.

**Comment by zmeadows** [comment]
I've now fixed the build issues on macOS and added build instructions to the Readme. I also added some github actions to test the build on linux/macOS for each commit to catch these sorts of issues in the future.

Please let me know if this didn't fix everything!

**Comment by IvanAli** [comment]
Thanks so much for looking into this :-)
